title: MehrdadLinux Weblog
author:
  name: MehrdadLinux
  email: MehrdadLinux@Gmail.Com
description: >- # this means to ignore newlines until "baseurl:"
 Technical diaries
show_excerpts: true
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
minima:
  date_format: "%b %-d, %Y"
  social_links:
      twitter: Mehrdadlinux
      github: MehrdadLinux
      devto: MehrdadLinux
      instagram: MehrdadLinux
      linkedin: MehrdadLinux
      youtube: mehrdadlinux
      telegram: MehrdadLinux
      disqus: mehrdadlinux
plugins:
  - jekyll-feed
  - jekyll-sitemap

theme: minima

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-7STP1PTFPR          # Required - replace with your tracking id
    anonymizeIp: true      # Optional - Default: false - set to true for anonymized tracking

google_analytics: G-7STP1PTFPR





 # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this


  # generate social links in footer

    # 
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # 
    # 
    # pinterest: jekyll
    # 
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # 
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
